# Generated by Django 5.0.2 on 2024-02-27 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
